# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogoGaudete(object):
    def setupUi(self, DialogoGaudete):
        DialogoGaudete.setObjectName("DialogoGaudete")
        DialogoGaudete.resize(1038, 812)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogoGaudete.sizePolicy().hasHeightForWidth())
        DialogoGaudete.setSizePolicy(sizePolicy)
        DialogoGaudete.setMinimumSize(QtCore.QSize(355, 200))
        DialogoGaudete.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(DialogoGaudete)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(DialogoGaudete)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 2, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(DialogoGaudete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.cbx_idiomas = QtWidgets.QComboBox(DialogoGaudete)
        self.cbx_idiomas.setObjectName("cbx_idiomas")
        self.horizontalLayout_8.addWidget(self.cbx_idiomas)
        self.btn_corpus = QtWidgets.QPushButton(DialogoGaudete)
        self.btn_corpus.setObjectName("btn_corpus")
        self.horizontalLayout_8.addWidget(self.btn_corpus)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.lbl_sinonimos = QtWidgets.QLabel(DialogoGaudete)
        self.lbl_sinonimos.setObjectName("lbl_sinonimos")
        self.gridLayout.addWidget(self.lbl_sinonimos, 9, 2, 1, 1)
        self.chk_audio = QtWidgets.QCheckBox(DialogoGaudete)
        self.chk_audio.setObjectName("chk_audio")
        self.gridLayout.addWidget(self.chk_audio, 13, 2, 1, 1)
        self.sll_ejemplos = QtWidgets.QScrollArea(DialogoGaudete)
        self.sll_ejemplos.setWidgetResizable(True)
        self.sll_ejemplos.setObjectName("sll_ejemplos")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -803, 484, 1376))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbn_ejemplo0 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo0.setText("")
        self.rbn_ejemplo0.setObjectName("rbn_ejemplo0")
        self.btng_ejemplos = QtWidgets.QButtonGroup(DialogoGaudete)
        self.btng_ejemplos.setObjectName("btng_ejemplos")
        self.btng_ejemplos.addButton(self.rbn_ejemplo0)
        self.gridLayout_3.addWidget(self.rbn_ejemplo0, 0, 0, 1, 1)
        self.txt_ejemplo3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo3.setObjectName("txt_ejemplo3")
        self.gridLayout_3.addWidget(self.txt_ejemplo3, 3, 2, 1, 1)
        self.txt_ejemplo5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo5.setObjectName("txt_ejemplo5")
        self.gridLayout_3.addWidget(self.txt_ejemplo5, 5, 2, 1, 1)
        self.txt_ejemplo9 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo9.setObjectName("txt_ejemplo9")
        self.gridLayout_3.addWidget(self.txt_ejemplo9, 9, 2, 1, 1)
        self.rbn_ejemplo1 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo1.setText("")
        self.rbn_ejemplo1.setObjectName("rbn_ejemplo1")
        self.btng_ejemplos.addButton(self.rbn_ejemplo1)
        self.gridLayout_3.addWidget(self.rbn_ejemplo1, 1, 0, 1, 1)
        self.rbn_ejemplo5 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo5.setText("")
        self.rbn_ejemplo5.setObjectName("rbn_ejemplo5")
        self.btng_ejemplos.addButton(self.rbn_ejemplo5)
        self.gridLayout_3.addWidget(self.rbn_ejemplo5, 5, 0, 1, 1)
        self.rbn_ejemplo10 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo10.setText("")
        self.rbn_ejemplo10.setObjectName("rbn_ejemplo10")
        self.btng_ejemplos.addButton(self.rbn_ejemplo10)
        self.gridLayout_3.addWidget(self.rbn_ejemplo10, 10, 0, 1, 1)
        self.rbn_ejemplo7 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo7.setText("")
        self.rbn_ejemplo7.setObjectName("rbn_ejemplo7")
        self.btng_ejemplos.addButton(self.rbn_ejemplo7)
        self.gridLayout_3.addWidget(self.rbn_ejemplo7, 7, 0, 1, 1)
        self.rbn_ejemplo6 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo6.setText("")
        self.rbn_ejemplo6.setObjectName("rbn_ejemplo6")
        self.btng_ejemplos.addButton(self.rbn_ejemplo6)
        self.gridLayout_3.addWidget(self.rbn_ejemplo6, 6, 0, 1, 1)
        self.rbn_ejemplo9 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo9.setText("")
        self.rbn_ejemplo9.setObjectName("rbn_ejemplo9")
        self.btng_ejemplos.addButton(self.rbn_ejemplo9)
        self.gridLayout_3.addWidget(self.rbn_ejemplo9, 9, 0, 1, 1)
        self.rbn_ejemplo13 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo13.setText("")
        self.rbn_ejemplo13.setObjectName("rbn_ejemplo13")
        self.btng_ejemplos.addButton(self.rbn_ejemplo13)
        self.gridLayout_3.addWidget(self.rbn_ejemplo13, 13, 0, 1, 1)
        self.rbn_ejemplo14 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo14.setText("")
        self.rbn_ejemplo14.setObjectName("rbn_ejemplo14")
        self.btng_ejemplos.addButton(self.rbn_ejemplo14)
        self.gridLayout_3.addWidget(self.rbn_ejemplo14, 14, 0, 1, 1)
        self.txt_ejemplo7 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo7.setObjectName("txt_ejemplo7")
        self.gridLayout_3.addWidget(self.txt_ejemplo7, 7, 2, 1, 1)
        self.txt_ejemplo14 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo14.setObjectName("txt_ejemplo14")
        self.gridLayout_3.addWidget(self.txt_ejemplo14, 14, 2, 1, 1)
        self.rbn_ejemplo12 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo12.setText("")
        self.rbn_ejemplo12.setObjectName("rbn_ejemplo12")
        self.btng_ejemplos.addButton(self.rbn_ejemplo12)
        self.gridLayout_3.addWidget(self.rbn_ejemplo12, 12, 0, 1, 1)
        self.txt_ejemplo13 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo13.setObjectName("txt_ejemplo13")
        self.gridLayout_3.addWidget(self.txt_ejemplo13, 13, 2, 1, 1)
        self.txt_ejemplo12 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo12.setObjectName("txt_ejemplo12")
        self.gridLayout_3.addWidget(self.txt_ejemplo12, 12, 2, 1, 1)
        self.rbn_ejemplo11 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo11.setText("")
        self.rbn_ejemplo11.setObjectName("rbn_ejemplo11")
        self.btng_ejemplos.addButton(self.rbn_ejemplo11)
        self.gridLayout_3.addWidget(self.rbn_ejemplo11, 11, 0, 1, 1)
        self.txt_ejemplo11 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo11.setObjectName("txt_ejemplo11")
        self.gridLayout_3.addWidget(self.txt_ejemplo11, 11, 2, 1, 1)
        self.txt_ejemplo10 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo10.setObjectName("txt_ejemplo10")
        self.gridLayout_3.addWidget(self.txt_ejemplo10, 10, 2, 1, 1)
        self.rbn_ejemplo3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo3.setText("")
        self.rbn_ejemplo3.setObjectName("rbn_ejemplo3")
        self.btng_ejemplos.addButton(self.rbn_ejemplo3)
        self.gridLayout_3.addWidget(self.rbn_ejemplo3, 3, 0, 1, 1)
        self.rbn_ejemplo4 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo4.setText("")
        self.rbn_ejemplo4.setObjectName("rbn_ejemplo4")
        self.btng_ejemplos.addButton(self.rbn_ejemplo4)
        self.gridLayout_3.addWidget(self.rbn_ejemplo4, 4, 0, 1, 1)
        self.txt_ejemplo8 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo8.setObjectName("txt_ejemplo8")
        self.gridLayout_3.addWidget(self.txt_ejemplo8, 8, 2, 1, 1)
        self.rbn_ejemplo2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo2.setText("")
        self.rbn_ejemplo2.setObjectName("rbn_ejemplo2")
        self.btng_ejemplos.addButton(self.rbn_ejemplo2)
        self.gridLayout_3.addWidget(self.rbn_ejemplo2, 2, 0, 1, 1)
        self.txt_ejemplo6 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo6.setObjectName("txt_ejemplo6")
        self.gridLayout_3.addWidget(self.txt_ejemplo6, 6, 2, 1, 1)
        self.txt_ejemplo1 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo1.setObjectName("txt_ejemplo1")
        self.gridLayout_3.addWidget(self.txt_ejemplo1, 1, 2, 1, 1)
        self.rbn_ejemplo8 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbn_ejemplo8.setText("")
        self.rbn_ejemplo8.setObjectName("rbn_ejemplo8")
        self.btng_ejemplos.addButton(self.rbn_ejemplo8)
        self.gridLayout_3.addWidget(self.rbn_ejemplo8, 8, 0, 1, 1)
        self.txt_ejemplo4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo4.setObjectName("txt_ejemplo4")
        self.gridLayout_3.addWidget(self.txt_ejemplo4, 4, 2, 1, 1)
        self.txt_ejemplo2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo2.setObjectName("txt_ejemplo2")
        self.gridLayout_3.addWidget(self.txt_ejemplo2, 2, 2, 1, 1)
        self.txt_ejemplo0 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.txt_ejemplo0.setObjectName("txt_ejemplo0")
        self.gridLayout_3.addWidget(self.txt_ejemplo0, 0, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_ejemplos_retrocede = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_ejemplos_retrocede.setObjectName("btn_ejemplos_retrocede")
        self.horizontalLayout_9.addWidget(self.btn_ejemplos_retrocede)
        self.btn_ejemplos_avanza = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_ejemplos_avanza.setObjectName("btn_ejemplos_avanza")
        self.horizontalLayout_9.addWidget(self.btn_ejemplos_avanza)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 15, 2, 1, 1)
        self.sll_ejemplos.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.sll_ejemplos, 3, 1, 12, 1)
        self.lbl_definicion = QtWidgets.QLabel(DialogoGaudete)
        self.lbl_definicion.setObjectName("lbl_definicion")
        self.gridLayout.addWidget(self.lbl_definicion, 11, 2, 1, 1)
        self.line_sinonimos = QtWidgets.QLineEdit(DialogoGaudete)
        self.line_sinonimos.setObjectName("line_sinonimos")
        self.gridLayout.addWidget(self.line_sinonimos, 10, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chk_footer2 = QtWidgets.QCheckBox(DialogoGaudete)
        self.chk_footer2.setText("")
        self.chk_footer2.setObjectName("chk_footer2")
        self.horizontalLayout_2.addWidget(self.chk_footer2)
        self.txt_footer2 = QtWidgets.QTextEdit(DialogoGaudete)
        self.txt_footer2.setObjectName("txt_footer2")
        self.horizontalLayout_2.addWidget(self.txt_footer2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancelar = QtWidgets.QPushButton(DialogoGaudete)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.btn_anadir = QtWidgets.QPushButton(DialogoGaudete)
        self.btn_anadir.setObjectName("btn_anadir")
        self.horizontalLayout.addWidget(self.btn_anadir)
        self.gridLayout.addLayout(self.horizontalLayout, 14, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(DialogoGaudete)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.line_palabra_buscar = QtWidgets.QLineEdit(DialogoGaudete)
        self.line_palabra_buscar.setObjectName("line_palabra_buscar")
        self.horizontalLayout_7.addWidget(self.line_palabra_buscar)
        self.sbn_cantidad_ejemplos = QtWidgets.QSpinBox(DialogoGaudete)
        self.sbn_cantidad_ejemplos.setMinimum(3)
        self.sbn_cantidad_ejemplos.setMaximum(15)
        self.sbn_cantidad_ejemplos.setProperty("value", 5)
        self.sbn_cantidad_ejemplos.setObjectName("sbn_cantidad_ejemplos")
        self.horizontalLayout_7.addWidget(self.sbn_cantidad_ejemplos)
        self.btn_buscar = QtWidgets.QPushButton(DialogoGaudete)
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout_7.addWidget(self.btn_buscar)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chk_header1 = QtWidgets.QCheckBox(DialogoGaudete)
        self.chk_header1.setText("")
        self.chk_header1.setObjectName("chk_header1")
        self.horizontalLayout_6.addWidget(self.chk_header1)
        self.txt_header1 = QtWidgets.QTextEdit(DialogoGaudete)
        self.txt_header1.setObjectName("txt_header1")
        self.horizontalLayout_6.addWidget(self.txt_header1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 2, 1, 1)
        self.txt_huecos = QtWidgets.QTextEdit(DialogoGaudete)
        self.txt_huecos.setObjectName("txt_huecos")
        self.gridLayout.addWidget(self.txt_huecos, 3, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chk_footer1 = QtWidgets.QCheckBox(DialogoGaudete)
        self.chk_footer1.setText("")
        self.chk_footer1.setObjectName("chk_footer1")
        self.horizontalLayout_3.addWidget(self.chk_footer1)
        self.txt_footer1 = QtWidgets.QTextEdit(DialogoGaudete)
        self.txt_footer1.setObjectName("txt_footer1")
        self.horizontalLayout_3.addWidget(self.txt_footer1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 2, 1, 1)
        self.line_definicion = QtWidgets.QLineEdit(DialogoGaudete)
        self.line_definicion.setObjectName("line_definicion")
        self.gridLayout.addWidget(self.line_definicion, 12, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chk_header2 = QtWidgets.QCheckBox(DialogoGaudete)
        self.chk_header2.setText("")
        self.chk_header2.setObjectName("chk_header2")
        self.horizontalLayout_5.addWidget(self.chk_header2)
        self.txt_header2 = QtWidgets.QTextEdit(DialogoGaudete)
        self.txt_header2.setObjectName("txt_header2")
        self.horizontalLayout_5.addWidget(self.txt_header2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(DialogoGaudete)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.btn_fotogramas = QtWidgets.QPushButton(DialogoGaudete)
        self.btn_fotogramas.setObjectName("btn_fotogramas")
        self.verticalLayout.addWidget(self.btn_fotogramas)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.frm_fotograma = QtWidgets.QLabel(DialogoGaudete)
        self.frm_fotograma.setMinimumSize(QtCore.QSize(355, 120))
        self.frm_fotograma.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_fotograma.setText("")
        self.frm_fotograma.setObjectName("frm_fotograma")
        self.horizontalLayout_4.addWidget(self.frm_fotograma)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(DialogoGaudete)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(DialogoGaudete)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)

        self.retranslateUi(DialogoGaudete)
        QtCore.QMetaObject.connectSlotsByName(DialogoGaudete)
        DialogoGaudete.setTabOrder(self.line_palabra_buscar, self.cbx_idiomas)
        DialogoGaudete.setTabOrder(self.cbx_idiomas, self.sbn_cantidad_ejemplos)
        DialogoGaudete.setTabOrder(self.sbn_cantidad_ejemplos, self.btn_buscar)
        DialogoGaudete.setTabOrder(self.btn_buscar, self.rbn_ejemplo0)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo0, self.txt_ejemplo0)
        DialogoGaudete.setTabOrder(self.txt_ejemplo0, self.rbn_ejemplo1)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo1, self.txt_ejemplo1)
        DialogoGaudete.setTabOrder(self.txt_ejemplo1, self.rbn_ejemplo2)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo2, self.txt_ejemplo2)
        DialogoGaudete.setTabOrder(self.txt_ejemplo2, self.rbn_ejemplo3)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo3, self.txt_ejemplo3)
        DialogoGaudete.setTabOrder(self.txt_ejemplo3, self.rbn_ejemplo4)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo4, self.txt_ejemplo4)
        DialogoGaudete.setTabOrder(self.txt_ejemplo4, self.rbn_ejemplo5)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo5, self.txt_ejemplo5)
        DialogoGaudete.setTabOrder(self.txt_ejemplo5, self.rbn_ejemplo6)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo6, self.txt_ejemplo6)
        DialogoGaudete.setTabOrder(self.txt_ejemplo6, self.rbn_ejemplo7)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo7, self.txt_ejemplo7)
        DialogoGaudete.setTabOrder(self.txt_ejemplo7, self.rbn_ejemplo8)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo8, self.txt_ejemplo8)
        DialogoGaudete.setTabOrder(self.txt_ejemplo8, self.rbn_ejemplo9)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo9, self.txt_ejemplo9)
        DialogoGaudete.setTabOrder(self.txt_ejemplo9, self.rbn_ejemplo10)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo10, self.txt_ejemplo10)
        DialogoGaudete.setTabOrder(self.txt_ejemplo10, self.rbn_ejemplo11)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo11, self.txt_ejemplo11)
        DialogoGaudete.setTabOrder(self.txt_ejemplo11, self.rbn_ejemplo12)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo12, self.txt_ejemplo12)
        DialogoGaudete.setTabOrder(self.txt_ejemplo12, self.rbn_ejemplo13)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo13, self.txt_ejemplo13)
        DialogoGaudete.setTabOrder(self.txt_ejemplo13, self.rbn_ejemplo14)
        DialogoGaudete.setTabOrder(self.rbn_ejemplo14, self.txt_ejemplo14)
        DialogoGaudete.setTabOrder(self.txt_ejemplo14, self.btn_ejemplos_retrocede)
        DialogoGaudete.setTabOrder(self.btn_ejemplos_retrocede, self.btn_ejemplos_avanza)
        DialogoGaudete.setTabOrder(self.btn_ejemplos_avanza, self.chk_header1)
        DialogoGaudete.setTabOrder(self.chk_header1, self.txt_header1)
        DialogoGaudete.setTabOrder(self.txt_header1, self.chk_header2)
        DialogoGaudete.setTabOrder(self.chk_header2, self.txt_header2)
        DialogoGaudete.setTabOrder(self.txt_header2, self.txt_huecos)
        DialogoGaudete.setTabOrder(self.txt_huecos, self.btn_fotogramas)
        DialogoGaudete.setTabOrder(self.btn_fotogramas, self.chk_footer1)
        DialogoGaudete.setTabOrder(self.chk_footer1, self.txt_footer1)
        DialogoGaudete.setTabOrder(self.txt_footer1, self.chk_footer2)
        DialogoGaudete.setTabOrder(self.chk_footer2, self.txt_footer2)
        DialogoGaudete.setTabOrder(self.txt_footer2, self.line_sinonimos)
        DialogoGaudete.setTabOrder(self.line_sinonimos, self.line_definicion)
        DialogoGaudete.setTabOrder(self.line_definicion, self.chk_audio)
        DialogoGaudete.setTabOrder(self.chk_audio, self.btn_cancelar)
        DialogoGaudete.setTabOrder(self.btn_cancelar, self.btn_anadir)
        DialogoGaudete.setTabOrder(self.btn_anadir, self.sll_ejemplos)
        DialogoGaudete.setTabOrder(self.sll_ejemplos, self.btn_corpus)

    def retranslateUi(self, DialogoGaudete):
        _translate = QtCore.QCoreApplication.translate
        DialogoGaudete.setWindowTitle(_translate("DialogoGaudete", "Dialog"))
        self.label_3.setText(_translate("DialogoGaudete", "Pie de la tarjeta:"))
        self.label.setText(_translate("DialogoGaudete", "Selecciona un idioma:"))
        self.btn_corpus.setText(_translate("DialogoGaudete", "Indexar Corpus"))
        self.lbl_sinonimos.setText(_translate("DialogoGaudete", "Sinónimos / Antónimos:"))
        self.chk_audio.setText(_translate("DialogoGaudete", "Incluir audio"))
        self.btn_ejemplos_retrocede.setText(_translate("DialogoGaudete", "<"))
        self.btn_ejemplos_avanza.setText(_translate("DialogoGaudete", ">"))
        self.lbl_definicion.setText(_translate("DialogoGaudete", "Definición:"))
        self.btn_cancelar.setText(_translate("DialogoGaudete", "Cancelar"))
        self.btn_anadir.setText(_translate("DialogoGaudete", "Añadir"))
        self.label_6.setText(_translate("DialogoGaudete", "Palabra o expresión regular:"))
        self.btn_buscar.setText(_translate("DialogoGaudete", "Buscar"))
        self.label_2.setText(_translate("DialogoGaudete", "Fotograma:"))
        self.btn_fotogramas.setText(_translate("DialogoGaudete", "+"))
        self.label_4.setText(_translate("DialogoGaudete", "Encabezado de la tarjeta:"))
        self.label_5.setText(_translate("DialogoGaudete", "TFG \"Apoyo al estudio de idiomas mediante tarjetas multimedia\" @ ASG 2023"))
